### ISSUE TITLE
dataset download agreement

### ISSUE THREAD

**Issue by mmmaat** [andi611/ZeroSpeech-TTS-without-T#1]
Hi,

Thanks for your contribution to the challenge. As an organizer I disagree with your [prepare date](https://github.com/andi611/ZeroSpeech-TTS-without-T#prepare-data) section in the README. Please correct it so as to **remove the password and redirect the users to the agreement**. Moreover please to **not distribute the surprise dataset as an external link** to google drive, this is explicitly forbidden by the agreement (but for private use it is OK).

The section can become something like:

1. **Download the ZeroSpeech dataset.**

    * The English dataset:
        ```
        wget https://download.zerospeech.com/2019/english.tgz
        tar xvfz english.tgz -C data
        rm -f english.tgz
        ```

    * The Surprise dataset:
        ```
        wget https://download.zerospeech.com/2019/surprise.zip
        # Go to https://download.zerospeech.com  and accept the licence agreement 
        # to get the password protecting the archive
        unzip surprise.zip -d data
        rm -f surprise.zip
        ```

Thank you,
Mathieu, for the ZeroSpeech team

**Comment by andi611** [comment]
Sorry for the delay, the violated section is fixed as requested.
