### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by caopan16** [andi611/ZeroSpeech-TTS-without-T#2]
Hi, I'm interested in this project, so I want to try your pre-trained models, How can I get it? Thank you.

**Comment by beknazar** [comment]
Yes, I am also interested.

**Comment by jonewei** [comment]
hi,I encounter this error when I run this project.FileNotFoundError: [Errno 2] No such file or directory: './hps/zerospeech_english.json'？How to solve this problem, please?

**Comment by andi611** [comment]
Pre-trained models are provided in the link below:
[bit.ly/ZeroSpeech2019-Liu](https://bit.ly/ZeroSpeech2019-Liu)

> hi,I encounter this error when I run this project.FileNotFoundError: [Errno 2] No such file or directory: './hps/zerospeech_english.json'？How to solve this problem, please?

The above error can be simply resolved by checking the `--hps_path` argument in `main.py`. Make sure that `--hps_path` is set to the correct path as the `your_path/*.json` file.
