### ISSUE TITLE
Why without T?

### ISSUE THREAD

**Issue by lucasjinreal** [andi611/ZeroSpeech-TTS-without-T#3]
Without T, simply produce voice from voice? What's the meaning of that?

**Comment by andi611** [comment]
TTS-w/o-T is the intended goal of the ZeroSpeech 2019 Challenge, which is described here with full detail: https://zerospeech.com/2019/. However, it is true that a voice-to-voice scheme is more like voice conversion, as we have discussed in our paper: https://arxiv.org/abs/1905.11563

**Comment by rishikksh20** [comment]
@andi611 It should be like while training you don't required transcription , model it self extract from audio file and get train. While Inference or testing, you just remove ASR part and put only text and get audio (like vanilla TTS).

**Comment by lucasjinreal** [comment]
@rishikksh20  I don't think you can train a model unsupervised and feed it supervised while inference.

For voice conversion, what's the input of model? Using my self voice to generate my own voice?

**Comment by andi611** [comment]
@rishikksh20 Yes, but then you would need to map human text to the machine-discovered discrete units. Then you can remove ASR, input text, map it to discrete units, then TTS generates speech from the learned units.

@jinfagang for a voice conversion model, the input is speech from a source speaker, and the output should be speech of the same content, but with the voice of a given target speaker.
