### ISSUE TITLE
KeyError: "Unable to open object (object 'V001' doesn't exist)"

### ISSUE THREAD

**Issue by ZhengRachel** [andi611/ZeroSpeech-TTS-without-T#7]
Hi~
I do have downloaded the dataset as you said in README.md，but I still encounter this error while doing the preprocessing:
[Processor] - making stage 2 training target samples with segment length =  128
[Sampler] - Generating stage 2 training target segments...
[Sampler] - Speaker used:  ['V001', 'V002']
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 126, in main
    remake=args.remake)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 73, in preprocess
    dset=dset)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 118, in make_samples
    sampler = Sampler(h5py_path, dset, seg_len, speaker2id_path, make_object)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 159, in __init__
    self.speaker2utts = {speaker : sorted(list(self.f_h5[f'{dset}/{speaker}'].keys())) for speaker in self.speaker_used}
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 159, in <dictcomp>
    self.speaker2utts = {speaker : sorted(list(self.f_h5[f'{dset}/{speaker}'].keys())) for speaker in self.speaker_used}
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\Anaconda\envs\TTSnoT\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'V001' doesn't exist)"
How can I fix it ?
It would be so kind of you if you could relpy me~

**Comment by andi611** [comment]
Hi,

It looks like the `self.f_h5` does not exist in this [line](https://github.com/andi611/ZeroSpeech-TTS-without-T/blob/0fb20fa5ab6af5b827858eaa381ddff6df30cf3c/preprocess.py#L159).
Please make sure that it is generated correctly in these lines: [here](https://github.com/andi611/ZeroSpeech-TTS-without-T/blob/0fb20fa5ab6af5b827858eaa381ddff6df30cf3c/preprocess.py#L39-L47)
Use the `--remake` argument during preprocessing.

Andy

**Comment by ZhengRachel** [comment]
Hi~I do use the command "python main.py --preprocess --remake" but it still generates this error and I don't know why orz @andi611

**Comment by ZhengRachel** [comment]
And it has done these steps:
[Processor] - making training dataset...
[Processor] - processing oice\V001: ./data/english/train/voice\V001_4294476796.wav - padded to (129, 513)
[Processor] - processing oice\V002: ./data/english/train/voice\V002_4292252342.wav - padded to (129, 513)
[Processor] - making testing dataset...
[Processor] - making stage 1 training samples with segment length =  128
[Processor] - making stage 2 training source samples with segment length =  128
[Processor] - making stage 2 training target samples with segment length =  128
[Sampler] - Generating stage 2 training target segments...
[Sampler] - Speaker used:  ['V001', 'V002']
[Processor] - making stage 2 training target samples with segment length =  128
[Sampler] - Generating stage 2 training target segments...
[Sampler] - Speaker used:  ['V001', 'V002'] and the error occurs while running this step
@andi611

**Comment by andi611** [comment]
> [Sampler] - Generating stage 2 training **target segments**...
> [Sampler] - Speaker used: ['V001', 'V002']
> [Sampler] - Generating stage 2 training **target segments**...
> [Sampler] - Speaker used: ['V001', 'V002']

Did you change the original code?
if you see [here](https://github.com/andi611/ZeroSpeech-TTS-without-T/blob/0fb20fa5ab6af5b827858eaa381ddff6df30cf3c/preprocess.py#L58-L73), **source segments** should be sampled first, next the **target segments**.
However, in your log, **target segments** are sampled twice.
Maybe you should clone this repo again, as other people running this script did not encounter this error.

**Comment by ZhengRachel** [comment]
Hi~ Sorry to bother but I still can't solve this problem T_T  @andi611 
I didn't change the original code, but as you say I still reclone this repo and rerun this code, and I am encountering this error again...
I copy the entire output while running the code with `python main.py --preprocess --remake` command as follows:
`(TTSnoT) F:\TTSwithoutT\try2>python main.py --preprocess --remake
[Runner] - Dataset:  english
[HPS Loader] - Loading from:  ./hps/zerospeech_english.json
[Runner] - Generation mode:  with generator
[Runner] - Generator mode:  targeted_residual
[Runner] - Encoder mode:  multilabel_binary
[Runner] - Encoding dim:  6
[Processor] - making training dataset...
Number of speakers:  100
[Processor] - processing unit\S015: ./data/english/train/unit\S015_4279698902.wav
[Processor] - processing unit\S020: ./data/english/train/unit\S020_4159549429.wav - padded to (129, 513)
[Processor] - processing unit\S021: ./data/english/train/unit\S021_4233403760.wav
[Processor] - processing unit\S023: ./data/english/train/unit\S023_4224407879.wav
[Processor] - processing unit\S027: ./data/english/train/unit\S027_4283980832.wav
[Processor] - processing unit\S031: ./data/english/train/unit\S031_4231303174.wav
[Processor] - processing unit\S032: ./data/english/train/unit\S032_4283884197.wav
[Processor] - processing unit\S033: ./data/english/train/unit\S033_4278207299.wav
[Processor] - processing unit\S034: ./data/english/train/unit\S034_4272730462.wav
[Processor] - processing unit\S035: ./data/english/train/unit\S035_4144899200.wav
[Processor] - processing unit\S036: ./data/english/train/unit\S036_4251991258.wav
[Processor] - processing unit\S037: ./data/english/train/unit\S037_4145687462.wav
[Processor] - processing unit\S038: ./data/english/train/unit\S038_4279509324.wav - padded to (129, 513)
[Processor] - processing unit\S039: ./data/english/train/unit\S039_4263619418.wav
[Processor] - processing unit\S040: ./data/english/train/unit\S040_4280282573.wav
[Processor] - processing unit\S041: ./data/english/train/unit\S041_4293249163.wav
[Processor] - processing unit\S042: ./data/english/train/unit\S042_4159081044.wav
[Processor] - processing unit\S043: ./data/english/train/unit\S043_4272517081.wav
[Processor] - processing unit\S044: ./data/english/train/unit\S044_4205157432.wav
[Processor] - processing unit\S045: ./data/english/train/unit\S045_4268968467.wav
[Processor] - processing unit\S046: ./data/english/train/unit\S046_4282490602.wav
[Processor] - processing unit\S047: ./data/english/train/unit\S047_4281332959.wav
[Processor] - processing unit\S048: ./data/english/train/unit\S048_4264108757.wav
[Processor] - processing unit\S049: ./data/english/train/unit\S049_4124180193.wav
[Processor] - processing unit\S050: ./data/english/train/unit\S050_4097484856.wav
[Processor] - processing unit\S051: ./data/english/train/unit\S051_4158134303.wav
[Processor] - processing unit\S052: ./data/english/train/unit\S052_4267617328.wav
[Processor] - processing unit\S053: ./data/english/train/unit\S053_4293622787.wav
[Processor] - processing unit\S054: ./data/english/train/unit\S054_4245687688.wav
[Processor] - processing unit\S055: ./data/english/train/unit\S055_4259678548.wav
[Processor] - processing unit\S056: ./data/english/train/unit\S056_4124642216.wav
[Processor] - processing unit\S058: ./data/english/train/unit\S058_4291855013.wav
[Processor] - processing unit\S059: ./data/english/train/unit\S059_4268115817.wav
[Processor] - processing unit\S060: ./data/english/train/unit\S060_4269391340.wav
[Processor] - processing unit\S061: ./data/english/train/unit\S061_4229211625.wav
[Processor] - processing unit\S063: ./data/english/train/unit\S063_4266863551.wav
[Processor] - processing unit\S064: ./data/english/train/unit\S064_4227292310.wav
[Processor] - processing unit\S065: ./data/english/train/unit\S065_4240568917.wav
[Processor] - processing unit\S066: ./data/english/train/unit\S066_4252994280.wav
[Processor] - processing unit\S067: ./data/english/train/unit\S067_4270309302.wav
[Processor] - processing unit\S069: ./data/english/train/unit\S069_4287444153.wav
[Processor] - processing unit\S070: ./data/english/train/unit\S070_4235505174.wav
[Processor] - processing unit\S071: ./data/english/train/unit\S071_4146103625.wav
[Processor] - processing unit\S072: ./data/english/train/unit\S072_4143381716.wav
[Processor] - processing unit\S073: ./data/english/train/unit\S073_4174160451.wav
[Processor] - processing unit\S074: ./data/english/train/unit\S074_4199590811.wav
[Processor] - processing unit\S075: ./data/english/train/unit\S075_4281373464.wav
[Processor] - processing unit\S076: ./data/english/train/unit\S076_4171284592.wav
[Processor] - processing unit\S077: ./data/english/train/unit\S077_4206044483.wav
[Processor] - processing unit\S078: ./data/english/train/unit\S078_4258916228.wav
[Processor] - processing unit\S079: ./data/english/train/unit\S079_4239524731.wav
[Processor] - processing unit\S080: ./data/english/train/unit\S080_4226272940.wav
[Processor] - processing unit\S082: ./data/english/train/unit\S082_4214755006.wav
[Processor] - processing unit\S083: ./data/english/train/unit\S083_4259686305.wav - padded to (129, 513)
[Processor] - processing unit\S084: ./data/english/train/unit\S084_4236188506.wav
[Processor] - processing unit\S085: ./data/english/train/unit\S085_4205749773.wav
[Processor] - processing unit\S086: ./data/english/train/unit\S086_4255192514.wav
[Processor] - processing unit\S087: ./data/english/train/unit\S087_4198389137.wav
[Processor] - processing unit\S088: ./data/english/train/unit\S088_4289657992.wav
[Processor] - processing unit\S090: ./data/english/train/unit\S090_4276962242.wav
[Processor] - processing unit\S091: ./data/english/train/unit\S091_4278435313.wav
[Processor] - processing unit\S092: ./data/english/train/unit\S092_4007631559.wav
[Processor] - processing unit\S093: ./data/english/train/unit\S093_4266720885.wav
[Processor] - processing unit\S094: ./data/english/train/unit\S094_4249918249.wav
[Processor] - processing unit\S095: ./data/english/train/unit\S095_4281300924.wav
[Processor] - processing unit\S096: ./data/english/train/unit\S096_4066563239.wav
[Processor] - processing unit\S097: ./data/english/train/unit\S097_4231385275.wav
[Processor] - processing unit\S098: ./data/english/train/unit\S098_4244639769.wav
[Processor] - processing unit\S099: ./data/english/train/unit\S099_4276830338.wav
[Processor] - processing unit\S100: ./data/english/train/unit\S100_4230522105.wav
[Processor] - processing unit\S101: ./data/english/train/unit\S101_4286773648.wav
[Processor] - processing unit\S102: ./data/english/train/unit\S102_4286306576.wav
[Processor] - processing unit\S103: ./data/english/train/unit\S103_4249647737.wav
[Processor] - processing unit\S104: ./data/english/train/unit\S104_4105425148.wav
[Processor] - processing unit\S105: ./data/english/train/unit\S105_4122444269.wav
[Processor] - processing unit\S106: ./data/english/train/unit\S106_4121902926.wav
[Processor] - processing unit\S107: ./data/english/train/unit\S107_4260020779.wav
[Processor] - processing unit\S109: ./data/english/train/unit\S109_4292837401.wav
[Processor] - processing unit\S110: ./data/english/train/unit\S110_4194690767.wav
[Processor] - processing unit\S111: ./data/english/train/unit\S111_4186548538.wav
[Processor] - processing unit\S112: ./data/english/train/unit\S112_4135844609.wav
[Processor] - processing unit\S113: ./data/english/train/unit\S113_4176887487.wav
[Processor] - processing unit\S114: ./data/english/train/unit\S114_4143374190.wav
[Processor] - processing unit\S115: ./data/english/train/unit\S115_4282175481.wav
[Processor] - processing unit\S116: ./data/english/train/unit\S116_4292713192.wav
[Processor] - processing unit\S117: ./data/english/train/unit\S117_4240772996.wav
[Processor] - processing unit\S118: ./data/english/train/unit\S118_3902855991.wav
[Processor] - processing unit\S119: ./data/english/train/unit\S119_4289669346.wav
[Processor] - processing unit\S120: ./data/english/train/unit\S120_4214217349.wav
[Processor] - processing unit\S121: ./data/english/train/unit\S121_4285886573.wav
[Processor] - processing unit\S122: ./data/english/train/unit\S122_4217344610.wav
[Processor] - processing unit\S123: ./data/english/train/unit\S123_4229342200.wav
[Processor] - processing unit\S125: ./data/english/train/unit\S125_4221726421.wav
[Processor] - processing unit\S126: ./data/english/train/unit\S126_4176952361.wav
[Processor] - processing unit\S127: ./data/english/train/unit\S127_4250428105.wav
[Processor] - processing unit\S128: ./data/english/train/unit\S128_4290093241.wav
[Processor] - processing unit\S129: ./data/english/train/unit\S129_4289165414.wav
[Processor] - processing unit\S131: ./data/english/train/unit\S131_4281913016.wav
[Processor] - processing unit\S132: ./data/english/train/unit\S132_4197275964.wav
[Processor] - processing unit\S133: ./data/english/train/unit\S133_4233390476.wav

Number of speakers:  2
[Processor] - processing oice\V001: ./data/english/train/voice\V001_4294476796.wav - padded to (129, 513)
[Processor] - processing oice\V002: ./data/english/train/voice\V002_4292252342.wav - padded to (129, 513)

[Processor] - making testing dataset...
Number of speakers:  24
[Processor] - processing test\S002: ./data/english/test\S002_4292819285.wav
[Processor] - processing test\S003: ./data/english/test\S003_4292426349.wav
[Processor] - processing test\S005: ./data/english/test\S005_4274307254.wav
[Processor] - processing test\S006: ./data/english/test\S006_4287513838.wav
[Processor] - processing test\S007: ./data/english/test\S007_4293615500.wav
[Processor] - processing test\S008: ./data/english/test\S008_4281015487.wav
[Processor] - processing test\S009: ./data/english/test\S009_4285228206.wav
[Processor] - processing test\S011: ./data/english/test\S011_4293907624.wav
[Processor] - processing test\S013: ./data/english/test\S013_4294641792.wav
[Processor] - processing test\S016: ./data/english/test\S016_4280405094.wav
[Processor] - processing test\S019: ./data/english/test\S019_4294810807.wav
[Processor] - processing test\S022: ./data/english/test\S022_4271084519.wav
[Processor] - processing test\S029: ./data/english/test\S029_4287038419.wav
[Processor] - processing test\S030: ./data/english/test\S030_4292167223.wav
[Processor] - processing test\S055: ./data/english/test\S055_4280898838.wav
[Processor] - processing test\S057: ./data/english/test\S057_4293378304.wav
[Processor] - processing test\S062: ./data/english/test\S062_4292598469.wav
[Processor] - processing test\S068: ./data/english/test\S068_4286710249.wav
[Processor] - processing test\S081: ./data/english/test\S081_4293304547.wav
[Processor] - processing test\S089: ./data/english/test\S089_4293653170.wav
[Processor] - processing test\S093: ./data/english/test\S093_4294123473.wav
[Processor] - processing test\S108: ./data/english/test\S108_4294144592.wav
[Processor] - processing test\S124: ./data/english/test\S124_4285316803.wav
[Processor] - processing test\S130: ./data/english/test\S130_4285111535.wav

[Processor] - making stage 1 training samples with segment length =  128
[Sampler] - Generating stage 1 training segments...
[Sampler] - Speaker used:  ['oice\\V001', 'oice\\V002', 'unit\\S015', 'unit\\S020', 'unit\\S021', 'unit\\S023', 'unit\\S027', 'unit\\S031', 'unit\\S032', 'unit\\S033', 'unit\\S034', 'unit\\S035', 'unit\\S036', 'unit\\S037', 'unit\\S038', 'unit\\S039', 'unit\\S040', 'unit\\S041', 'unit\\S042', 'unit\\S043', 'unit\\S044', 'unit\\S045', 'unit\\S046', 'unit\\S047', 'unit\\S048', 'unit\\S049', 'unit\\S050', 'unit\\S051', 'unit\\S052', 'unit\\S053', 'unit\\S054', 'unit\\S055', 'unit\\S056', 'unit\\S058', 'unit\\S059', 'unit\\S060', 'unit\\S061', 'unit\\S063', 'unit\\S064', 'unit\\S065', 'unit\\S066', 'unit\\S067', 'unit\\S069', 'unit\\S070', 'unit\\S071', 'unit\\S072', 'unit\\S073', 'unit\\S074', 'unit\\S075', 'unit\\S076', 'unit\\S077', 'unit\\S078', 'unit\\S079', 'unit\\S080', 'unit\\S082', 'unit\\S083', 'unit\\S084', 'unit\\S085', 'unit\\S086', 'unit\\S087', 'unit\\S088', 'unit\\S090', 'unit\\S091', 'unit\\S092', 'unit\\S093', 'unit\\S094', 'unit\\S095', 'unit\\S096', 'unit\\S097', 'unit\\S098', 'unit\\S099', 'unit\\S100', 'unit\\S101', 'unit\\S102', 'unit\\S103', 'unit\\S104', 'unit\\S105', 'unit\\S106', 'unit\\S107', 'unit\\S109', 'unit\\S110', 'unit\\S111', 'unit\\S112', 'unit\\S113', 'unit\\S114', 'unit\\S115', 'unit\\S116', 'unit\\S117', 'unit\\S118', 'unit\\S119', 'unit\\S120', 'unit\\S121', 'unit\\S122', 'unit\\S123', 'unit\\S125', 'unit\\S126', 'unit\\S127', 'unit\\S128', 'unit\\S129', 'unit\\S131', 'unit\\S132', 'unit\\S133']
[Sampler] - 0 too short utterences out of a total of 9474 are removed.

[Processor] - making stage 2 training source samples with segment length =  128
[Sampler] - Generating stage 2 training source segments...
[Sampler] - Speaker used:  ['oice\\V001', 'oice\\V002', 'unit\\S015', 'unit\\S020', 'unit\\S021', 'unit\\S023', 'unit\\S027', 'unit\\S031', 'unit\\S032', 'unit\\S033', 'unit\\S034', 'unit\\S035', 'unit\\S036', 'unit\\S037', 'unit\\S038', 'unit\\S039', 'unit\\S040', 'unit\\S041', 'unit\\S042', 'unit\\S043', 'unit\\S044', 'unit\\S045', 'unit\\S046', 'unit\\S047', 'unit\\S048', 'unit\\S049', 'unit\\S050', 'unit\\S051', 'unit\\S052', 'unit\\S053', 'unit\\S054', 'unit\\S055', 'unit\\S056', 'unit\\S058', 'unit\\S059', 'unit\\S060', 'unit\\S061', 'unit\\S063', 'unit\\S064', 'unit\\S065', 'unit\\S066', 'unit\\S067', 'unit\\S069', 'unit\\S070', 'unit\\S071', 'unit\\S072', 'unit\\S073', 'unit\\S074', 'unit\\S075', 'unit\\S076', 'unit\\S077', 'unit\\S078', 'unit\\S079', 'unit\\S080', 'unit\\S082', 'unit\\S083', 'unit\\S084', 'unit\\S085', 'unit\\S086', 'unit\\S087', 'unit\\S088', 'unit\\S090', 'unit\\S091', 'unit\\S092', 'unit\\S093', 'unit\\S094', 'unit\\S095', 'unit\\S096', 'unit\\S097', 'unit\\S098', 'unit\\S099', 'unit\\S100', 'unit\\S101', 'unit\\S102', 'unit\\S103', 'unit\\S104', 'unit\\S105', 'unit\\S106', 'unit\\S107', 'unit\\S109', 'unit\\S110', 'unit\\S111', 'unit\\S112', 'unit\\S113', 'unit\\S114', 'unit\\S115', 'unit\\S116', 'unit\\S117', 'unit\\S118', 'unit\\S119', 'unit\\S120', 'unit\\S121', 'unit\\S122', 'unit\\S123', 'unit\\S125', 'unit\\S126', 'unit\\S127', 'unit\\S128', 'unit\\S129', 'unit\\S131', 'unit\\S132', 'unit\\S133']
[Sampler] - 0 too short utterences out of a total of 9474 are removed.

[Processor] - making stage 2 training target samples with segment length =  128
[Sampler] - Generating stage 2 training target segments...
[Sampler] - Speaker used:  ['V001', 'V002']
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 126, in main
    remake=args.remake)
  File "F:\TTSwithoutT\try2\preprocess.py", line 73, in preprocess
    dset=dset)
  File "F:\TTSwithoutT\try2\preprocess.py", line 118, in make_samples
    sampler = Sampler(h5py_path, dset, seg_len, speaker2id_path, make_object)
  File "F:\TTSwithoutT\try2\preprocess.py", line 159, in __init__
    self.speaker2utts = {speaker : sorted(list(self.f_h5[f'{dset}/{speaker}'].keys())) for speaker in self.speaker_used}
  File "F:\TTSwithoutT\try2\preprocess.py", line 159, in <dictcomp>
    self.speaker2utts = {speaker : sorted(list(self.f_h5[f'{dset}/{speaker}'].keys())) for speaker in self.speaker_used}
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\Anaconda\envs\TTSnoT\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'V001' doesn't exist)"`

**Comment by andi611** [comment]
In your computer, the path looks like: `./data/english/test\S0XX_XXXXXXXX.wav`
with \ rather than "/".
This causes an error for string parsing, speakers should be like:
`[Sampler] - Speaker used: ['V001', 'V002', 'S015', 'S020', ...]`
However, the error results in a speaker list like:
`[Sampler] - Speaker used: ['oice\V001', 'oice\V002', 'unit\S015', 'unit\S020', ...]`

Hence in this [line](https://github.com/andi611/ZeroSpeech-TTS-without-T/blob/0fb20fa5ab6af5b827858eaa381ddff6df30cf3c/preprocess.py#L137), 'V001' doesn't exist, as it is now 'oice\V001'.

You can either fix your path (RECOMMENDED 1), or update the string parsing according to your path (RECOMMENDED 2), or change this [line](https://github.com/andi611/ZeroSpeech-TTS-without-T/blob/0fb20fa5ab6af5b827858eaa381ddff6df30cf3c/preprocess.py#L137) to `self.target_speakers = ['oice\V001', 'oice\V002']` (NOT RECOMMENDED).
